import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const base='http://127.0.0.1:3100';
async function role(value){await page.getByRole('button',{name:'Demo controls',exact:true}).click();await page.getByLabel('Demo role',{exact:true}).selectOption(value);await page.getByRole('button',{name:'Close demo controls',exact:true}).click();}
async function scene(value){await page.goto(base);await page.getByRole('button',{name:'Demo controls',exact:true}).click();await page.getByLabel('Demo scene',{exact:true}).selectOption(value);await page.getByRole('button',{name:'Load scene',exact:true}).click();await page.waitForURL(url=>url.pathname!=='/');await page.getByRole('button',{name:'Close demo controls',exact:true}).click();}
const checks=[];
await scene('venue-inquiry');await page.goto(base+'/venues');await page.getByLabel('Guests').fill('999');await expect(page.getByRole('heading',{name:'No sample venues match'})).toBeVisible();await page.getByRole('button',{name:'Clear filters',exact:true}).click();await page.getByLabel('Preferred date').fill('2026-11-08');await page.getByRole('link',{name:'View Sample Hall',exact:true}).click();await page.getByRole('button',{name:'Request a quote',exact:true}).click();await expect(page.getByLabel('Event starts (Philippine time)',{exact:true})).toHaveValue('2026-11-08T10:00');await page.getByLabel('Additional needs',{exact:true}).fill('Sample step-free access discussion');await page.reload();await expect(page.getByLabel('Additional needs',{exact:true})).toHaveValue('Sample step-free access discussion');checks.push('Filters, empty state, requested date and inquiry draft/step survive refresh');
const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(axe.violations).toEqual([]);checks.push('Open inquiry form axe scan: zero violations');
await scene('event-setup');await page.getByRole('button',{name:'2. Venue & layout',exact:true}).click();await page.getByText('Private messages & optional meetings',{exact:true}).click();await page.getByRole('button',{name:'Propose sample meeting',exact:true}).click();await role('venue');await page.goto(base+'/venue/events/makers-market-2026/review');await page.getByText('Private messages & optional meetings',{exact:true}).click();await page.getByRole('button',{name:'Suggest another time',exact:true}).click();await expect(page.getByText(/venue → organizer/)).toBeVisible();await role('organizer');await page.goto(base+'/organizer/events/makers-market-2026/setup');await page.getByText('Private messages & optional meetings',{exact:true}).click();await page.getByRole('button',{name:'Accept meeting',exact:true}).click();await page.getByRole('button',{name:'Cancel meeting',exact:true}).click();await expect(page.getByText('canceled',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Propose sample meeting',exact:true}).click();await role('venue');await page.goto(base+'/venue/events/makers-market-2026/review');await page.getByText('Private messages & optional meetings',{exact:true}).click();await page.getByRole('button',{name:'Decline meeting',exact:true}).click();await expect(page.getByText('declined',{exact:true})).toBeVisible();await expect(page.getByTestId('venue-agreement-status')).not.toHaveText('Agreed');checks.push('Meeting counter/recipient acceptance/cancel/decline preserve unagreed arrangement');
expect(errors).toEqual([]);fs.writeFileSync('docs/evidence/extra-check-results.json',JSON.stringify({at:new Date().toISOString(),checks,errors},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();
